class Globals {
  static final Map<String, String> sourceConfigs = {
    "Adevarul": "https://adevarul.ro/",
    "Antena3": "https://www.antena3.ro/",
    "Digi24": "https://www.digi24.ro/",
    "HotNews": "https://hotnews.ro/",
    "Libertatea": "https://www.libertatea.ro/",
    "RomaniaTV": "https://www.romaniatv.net/",
    "TVRInfo": "https://tvrinfo.ro/",

    // Good to go:
    // "stiripesurse": "https://www.stiripesurse.ro/",
    // "Agerpres": "https://agerpres.ro/",
    // "EuropaLibera": "https://romania.europalibera.org/", //https://romania.europalibera.org/stiri
    // "DCnews": "https://www.dcnews.ro/",
    // "G4media": "https://www.g4media.ro/", //green news + main page
    // "Profit": "https://www.profit.ro/", //stiri/politica si economie
    // "GreenNews": "https://greennews.ro/", //https://greennews.ro/stiri/
    // "economica.ro": "https://www.economica.net/",
    // "ForbesRomania": "https://www.forbes.ro/", //https://www.forbes.ro/actualitate
    // "CursdeGuvernare": "https://cursdeguvernare.ro/", //https://cursdeguvernare.ro/cat/stiri-2
    // "Retail-FMCG": "https://www.retail-fmcg.ro/",
    // "Juridice.ro": "https://www.juridice.ro/", //https://www.juridice.ro/flux-informatii
    // "RevistaProgresiv": "https://revistaprogresiv.ro/", //https://revistaprogresiv.ro/retail/
    // "euractiv": "https://www.euractiv.ro/",
    // "Retail.ro": "https://www.retail.ro/",

    //VERIFY
    // "RevistaBIZ": "https://www.revistabiz.ro/",
    // "360medical.ro": "https://www.360medical.ro/",
    // "MedicalNews": "https://www.medicalnews.ro/",
    // "UniversulJuridic.ro": "https://www.universuljuridic.ro/",
    // "Edupedu": "https://www.edupedu.ro/",

    // Dynamic, can't scrape
    // "WallStreetRomania": "https://www.wall-street.ro/",
    // "EuroNews": "https://www.euronews.ro/", //RSS Feed only for global feed



    // Site is not ok (missing bunch of info or hard to read)
    // "avocatnet.ro": "https://www.avocatnet.ro/",
    // "ZiarulFinanciar": "https://www.zf.ro/",
    // "rfi": "https://www.rfi.fr/ro/", //romania, europa, international
  };

  static Map<String, List<String>> storyTypeKeywords = {
    'General' : [],

    'Politică internă': [
      // Single words - Romanian specific
      'guvern', 'parlament', 'senat', 'ministru', 'ministrul',
      'premier', 'presedinte', 'politic', 'partid', 'coalitie',
      'opozitie', 'deputat', 'senator', 'vot', 'protest',
      'motiune', 'decret', 'ordonanta', 'primarie', 'consiliu',
      'legislativ', 'justitie', 'campanie', 'bolojan'

      // Multi-word phrases - explicitly Romanian
      'guvernul romaniei', 'guvernul de la bucuresti', 'executiv bucuresti',
      'prim ministru', 'prim-ministru', 'presedinte al romaniei',
      'presedintele romaniei', 'klaus iohannis', 'palatul cotroceni',
      'ministrul de interne', 'ministrul justitiei', 'ministrul de externe',
      'ministrul apararii', 'ministrul finantelor', 'ministrul sanatatii',
      'ministrul educatiei', 'ministrul transporturilor', 'ministru roman',
      'camera deputatilor', 'parlament romanesc', 'palatul parlamentului',
      'consiliul local', 'consiliul judetean', 'consiliul general',
      'primarul general', 'primarul capitalei', 'primarul bucurestiului',
      'primarul sectorului', 'primar local', 'prefect',
      'alegeri locale', 'alegeri parlamentare', 'alegeri prezidentiale',
      'campanie electorala', 'partid politic', 'lider politic',
      'sedinta de guvern', 'ordonanta de urgenta', 'hotarare de guvern',
      'coalitie de guvernare', 'motiune de cenzura', 'vot de incredere',
      'scandal politic', 'dezbatere parlamentara', 'ședință solemna',
      'sedinta plenului', 'comisie parlamentara', 'proiect de lege',
      'lege organica', 'constitutia romaniei', 'curtea constitutionala',
      'ccr', 'inalta curte', 'dosare penale', 'parchetul general',
      'dna', 'directia nationala anticoruptie', 'cercetare penala',
      'politica romaneasca', 'scena politica romaneasca', 'bucuresti politic',
      'psd', 'pnl', 'usr', 'aur', 'udmr', 'partidul social democrat',
      'partidul national liberal', 'usr-plus', 'alianta usr plus',
      'nicusor dan', 'gabriela firea', 'marcel ciolacu', 'nicolae ciuca',
      'parlament de la bucuresti', 'coalitia psd-pnl', 'coalitia de dreapta',
      'opozitia parlamentara', 'puterea de la bucuresti',
      'institutii romanesti', 'autoritati romane', 'oficiali romani',
      'liderii politici romani', 'clasa politica romaneasca', 'armatei romane',
      'la bucuresti'
    ],

    'World': [
      // Single words - international
      'ucraina', 'rusia', 'putin', 'international', 'strainatate',
      'conflict', 'criza', 'refugiat', 'refugiati', 'razboi',
      'summit', 'onu', 'sua', 'china', 'terorism', 'geopolitica',
      'ambasador', 'frontiera', 'granita', 'iran', 'america',
      'iraq', 'israel', 'gaza', 'syria', 'ungaria', 'suedia', 'orban', 'ucrain',
      'reinarmare'
      // Multi-word phrases - international focus
      'uniunea europeana', 'uniune europeana', 'statele unite', 'putere',
      'statele unite ale americii', 'casa alba', 'presedintele sua',
      'presedintele rusiei', 'vladimir putin', 'razboi in ucraina',
      'conflict armat', 'conflict militar', 'invazie rusa',
      'razboi ruso-ucrainean', 'criza refugiatilor', 'criza umanitara',
      'ajutor umanitar', 'organizatia natiunilor unite',
      'consiliul de securitate', 'adunarea generala onu',
      'summit nato', 'aliat nato', 'membru nato', 'tratatul nato',
      'articolul 5', 'nato summit', 'alianta atlanticului de nord',
      'summit european', 'consiliul european', 'comisia europeana',
      'parlament european', 'bruxelles', 'strasbourg',
      'lideri europeni', 'lideri mondiali', 'summit international',
      'politica externa', 'politica internationala', 'relatii diplomatice',
      'relatii bilaterale', 'relatii internationale',
      'ambasada sua', 'ambasador american', 'ambasador rus',
      'consilier prezidential american', 'secretar de stat american',
      'departamentul de stat', 'pentagon', 'kremlin',
      'conflict armat', 'zona de conflict', 'zona de razboi',
      'sanctiuni internationale', 'sanctiuni economice', 'embargo economic',
      'criza economica globala', 'tensiuni geopolitice', 'tensiuni regionale',
      'frontiera ucraineana', 'granita cu ucraina',
      'tari membre ue', 'state membre nato', 'tari occidentale',
      'occident', 'orientul mijlociu', 'orientul indepartat',
      'asia de sud', 'america latina', 'africa subsahariana',
      'stramtoare ormuz', 'conflict israelo-palestinian',
      'razboiul din gaza', 'hamas', 'hezbollah', 'fasia gaza',
      'conflict sirian', 'razboi civil', 'revolta araba',
      'primavara araba', 'atac terorist', 'grupare terorista',
      'stat islamic', 'al-qaida', 'atentate teroriste',
      'negocieri de pace', 'acord de pace', 'armistițiu',
      'cesare-focul', 'convorbiri de pace', 'summit g7', 'summit g20',
      'forumul economic mondial', 'davos', 'banca mondiala', 'fmi',
      'schimbari climatice globale', 'acordul de la paris',
      'summit climatic', 'cop summit',
      'migratia ilegala', 'criza migratorie', 'azilanti politici',
      'joe biden', 'donald trump', 'xi jinping', 'emmanuel macron',
      'angela merkel', 'olaf scholz', 'boris johnson', 'rishi sunak',
      'volodimir zelenski', 'volodymyr zelensky', 'benjamin netanyahu',
      'recep erdogan', 'narendra modi', 'lula da silva',
      'alegeri sua', 'alegeri americane', 'alegeri in sua',
      'alegeri in franta', 'alegeri in germania', 'alegeri in uk',
      'brexit', 'marea britanie', 'regatul unit', 'crown',
      'china continentala', 'taiwan', 'coreea de nord', 'coreea de sud',
      'japonia', 'india', 'pakistan', 'afganistan', 'turcia',
      'arabia saudita', 'emiratele arabe', 'egipt', 'libia',
      'conflict regional', 'conflict international', 'razboi global',
      'comunitate internationala', 'ordine mondiala', 'securitate globala',
    ],

    'Business': [
      // Single words
      'economie', 'taxe', 'impozit', 'salarii', 'bursa', 'inflatie',
      'finante', 'investitii', 'profit', 'piata', 'tranzactii', 'afaceri',
      'startup', 'antreprenor', 'venit', 'pib', 'buget', 'actiuni',
      'banca', 'credit', 'dobanda', 'imobiliare', 'energie', 'autostraz',
      'autostrada',
      // Multi-word phrases
      'bursa de valori', 'bursa de la bucuresti', 'piata de capital',
      'piata imobiliara', 'piata financiara', 'piata energiei',
      'indice bursier', 'tranzactii bursiere', 'investitii straine',
      'investitii directe', 'investitori straini', 'capital strain',
      'produsul intern brut', 'crestere economica', 'recesiune economica',
      'deficit bugetar', 'balanta comerciala', 'rata inflatiei',
      'inflatie anuala', 'cresterea preturilor', 'putere de cumparare',
      'salariul minim', 'salariu brut', 'salariu net', 'venit mediu',
      'crestere salariala', 'impozit pe venit', 'impozit pe profit',
      'taxa pe valoarea adaugata', 'cota unica', 'taxa auto',
      'taxe locale', 'aviz fiscal', 'banca nationala', 'bnr',
      'dobanda de politica monetara', 'rata dobanzii', 'credit ipotecar',
      'credit de consum', 'card de credit', 'rata creditului',
      'sector privat', 'sector public', 'companie privata',
      'companie listata', 'companie de stat', 'fondul monetar international',
      'fmi', 'banca mondiala', 'ue fonduri', 'fonduri europene',
      'programul pnrr', 'energie verde', 'energie regenerabila',
      'pret gaze', 'pret curent', 'pret petrol', 'baril petrol',
      'companie energetica', 'startup tehnologic', 'investitor angel',
      'capital de risc', 'finantare seed', 'turnoveri', 'cifra de afaceri',
      'blockchain technology', 'crypto monede'
    ],

    'Entertainment': [
      // Single words
      'film', 'muzica', 'teatru', 'serial', 'celebrity', 'star', 'show',
      'festival', 'concert', 'divertisment', 'artist', 'premiera',
      'eveniment', 'cinema', 'netflix', 'hollywood', 'oscar', 'grammy',
      'lifestyle', 'monden', 'influencer', 'vlogger', 'spectacol', 'cultura',
      'emisiune', 'zodii', 'zodie',
      // Multi-word phrases
      'premiera filmului', 'premiera mondiala', 'lansare film',
      'film romanesc', 'film hollywoodian', 'film de oscar',
      'cinema city', 'sala de cinema', 'box office', 'incasari record',
      'festival de film', 'festivalul de la cannes', 'festivalul de la venetia',
      'berlin film festival', 'festival international', 'premiile oscar',
      'premiile golden globe', 'premiile bafta', 'premiile emmy',
      'premiile grammy', 'gala premiilor', 'covorul rosu',
      'serial netflix', 'serial hbo', 'serial de succes', 'sezon nou',
      'ultimul sezon', 'episodul final', 'personaj principal',
      'streaming online', 'platforma streaming', 'serviciu streaming',
      'concert live', 'turneu national', 'turneu international',
      'turneu mondial', 'artist international', 'artist roman',
      'trupa de muzica', 'muzica live', 'spectacol muzical',
      'festival muzica', 'untold festival', 'electric castle',
      'neversea festival', 'festival george enescu', 'teatru national',
      'teatrul odeon', 'spectacol teatral', 'piesa de teatru',
      'premiera teatrala', 'festival teatru', 'bilet spectacol',
      'eveniment cultural', 'eveniment monden', 'petrecere privata',
      'nunta anului', 'divorț', 'cuplu celebrity', 'relatie amoroasa',
      'scandal monden', 'imagine sexy', 'aparitie provocatoare',
      'rochie spectaculoasa', 'outfit spectaculos', 'stil vestimentar',
      'fashion show', 'saptamana modei', 'influencer roman',
      'vedeta instagram', 'vedeta tiktok', 'vedeta youtube',
      'reality show', 'emisiune tv', 'emisiune divertisment',
      'prezentator tv', 'vedeta tv', 'star international',
      'celebritate mondiala', 'actrita premiata', 'actor premiat',
      'regizor premiat', 'cantaret de succes', 'castigator grammy',
      'artist consacrat', 'cariera artistica', 'viata personala',
      'viata amoroasa', 'imagine publica'
    ],

    'Știință și Tehnologie': [
      // Single words
      'tehnologie', 'descoperire', 'inovatie', 'software', 'hardware',
      'programare', 'robot', 'inteligenta artificiala', 'nasa', 'spatiu',
      'cercetare', 'cyber', 'securitate', 'gadget', 'smartphone', 'iphone',
      'android', 'metaverse', 'crypto', 'blockchain',
      // Multi-word phrases
      'inteligenta artificiala', 'invatare automata', 'machine learning',
      'deep learning', 'retele neuronale', 'algoritm ai',
      'chatbot ai', 'asistent virtual', 'robot industrial',
      'robotica avansata', 'masina autonoma', 'masina fara sofer',
      'vehicul autonom', 'tehnologie autonoma', 'tehnologie verde',
      'tehnologie curata', 'energie regenerabila', 'panouri solar',
      'energie solara', 'turbine eoliene', 'energie eoliana',
      'descoperire stiintifica', 'cercetare stiintifica', 'studiu stiintific',
      'institut de cercetare', 'laborator de cercetare',
      'universitate tehnica', 'cercetatori romani', 'savant roman',
      'premiu nobel', 'premiu pentru stiinta', 'cercetare medicala',
      'cercetare biologica', 'misiune spatiala', 'agentia spatiala',
      'nasa lansare', 'satelit spatial', 'statie spatiala',
      'telescop spatial', 'spatiul cosmic', 'explorare spatiala',
      'astronaut roman', 'zbor spatial', 'racheta spatiala',
      'elon musk', 'spacex lansare', 'jeff bezos', 'blue origin',
      'smartphone nou', 'telefon inteligent', 'model nou',
      'lansare iphone', 'iphone 16', 'samsung galaxy',
      'telefon android', 'sistem de operare', 'aplicatie mobila',
      'update software', 'versiune noua', 'lansare produs',
      'gadget tech', 'dispozitiv inteligent', 'casa inteligenta',
      'smart home', 'internet of things', 'iot device',
      'securitate cibernetica', 'atac cibernetic', 'hacker',
      'breach de securitate', 'furt de date', 'date personale',
      'protectia datelor', 'gdpr', 'criptare date',
      'parola de securitate', 'autentificare doi factori',
      'ransomware atac', 'virus informatic', 'malware',
      'realitate virtuala', 'realitate augmentata', 'vr headset',
      'oculus quest', 'metaverse platform', 'lume virtuala',
      'criptomoneda', 'bitcoin', 'ethereum', 'moneda digitala',
      'tehnologie blockchain', 'nft', 'token digital',
      'bursa crypto', 'miner bitcoin', 'wallet digital',
      'startup tehnologic', 'companie tech', 'gigant tech',
      'silicon valley', 'apple intelligence', 'microsoft ai',
      'google ai', 'openai', 'chatgpt', 'algoritm google',
      'motor de cautare', 'cloud computing', 'servicii cloud',
      'data center', 'server cloud', '5g network',
      'retea 5g', 'tehnologie 5g', 'laptop nou', 'procesor nou',
      'placa video', 'gpu', 'procesor intel', 'procesor amd',
      'chip procesor', 'semiconductori', 'microchip'
    ],

    'Health': [
      // Single words
      'sanatate', 'spital', 'medic', 'covid', 'vaccin', 'boala', 'tratament',
      'simptome', 'carantina', 'doctor', 'clinica', 'pacient', 'farmacie',
      'medicament', 'epidemie', 'pandemie', 'dieta', 'nutritie', 'microplastic',
      // Multi-word phrases
      'sistem sanitar', 'sistem medical', 'minister sanatatii',
      'ministrul sanatatii', 'spital de urgenta', 'spital clinic',
      'spital universitar', 'spital privat', 'spital de stat',
      'camera de garda', 'sectie ati', 'terapie intensiva',
      'urgente medicale', 'ambulanta smurd', 'asistenta medicala',
      'cadre medicale', 'medic specialist', 'medic de familie',
      'medic primar', 'chirurg renumit', 'doctor in medicina',
      'personal medical', 'greva medicilor', 'infectie respiratorie',
      'gripa sezoniera', 'virus gripal', 'infectie virala',
      'infectie bacteriana', 'boala cronica', 'boala rara',
      'boala infectioasa', 'diagnostic medical', 'analize medicale',
      'investigatii medicale', 'test medical', 'analize de sange',
      'radiografie', 'computer tomograf', 'rezonanta magnetica',
      'ecografie medicala', 'interventie chirurgicala',
      'operatie chirurgicala', 'transplant de organe',
      'chirurgie cardiovasculara', 'tratament medical',
      'schema de tratament', 'protocol medical', 'terapie medicala',
      'medicament nou', 'medicament inovator', 'efect secundar',
      'efecte adverse', 'reactie alergica', 'farmacie cu program',
      'reteta medicala', 'vaccin anti-covid', 'vaccin antigripal',
      'campanie de vaccinare', 'doza de vaccin', 'doza de rapel',
      'schema de vaccinare', 'imunizare completa', 'certificat verde',
      'pandemie covid', 'val pandemic', 'criza sanitara',
      'restrictii sanitare', 'masuri sanitare', 'izolare la domiciliu',
      'carantina obligatorie', 'test covid', 'test pcr', 'test antigen',
      'test rapid', 'infectare covid', 'caz confirmat',
      'numar de cazuri', 'rata de infectare', 'focar de infectie',
      'transmitere comunitara', 'transmitere virus', 'masca de protectie',
      'distantare sociala', 'dezinfectare', 'igiena mainilor',
      'simptome specifice', 'probleme respiratorii', 'febra ridicata',
      'raceala', 'tuse persistenta', 'dureri de cap', 'dureri musculare',
      'stare generala', 'sanatate publica', 'politica de sanatate',
      'reforme in sanatate', 'asigurari de sanatate', 'casa de sanatate',
      'casa nationala', 'card de sanatate', 'card european',
      'dieta echilibrata', 'nutritie sanatoasa', 'stil de viata',
      'stil de viata sanatos', 'alimentatie sanatoasa', 'sport regulat',
      'activitate fizica', 'sanatate mentala', 'sanitate psihica',
      'terapie psihologica', 'depresie clinica', 'anxietate',
      'tulburare psihica', 'boli cardiovasculare', 'infarct miocardic',
      'accident vascular', 'avc', 'diabet zaharat', 'cancer',
      'tumoare maligna', 'tratament oncologic', 'chimioterapie',
      'radioterapie', 'imunoterapie', 'boala alzheimer',
      'boala parkinson', 'scleroza multipla'
    ],

    'Sport': [
      // Single words
      'fotbal', 'sport', 'tenis', 'baschet', 'handbal', 'competitie',
      'campionat', 'olimpiada', 'echipa', 'meci', 'scor', 'gol',
      'antrenor', 'liga', 'halep', 'stelist', 'dinamovist', 'rapidist',
      // Multi-word phrases
      'echipa nationala', 'nationala romaniei', 'nationala de fotbal',
      'tricolorii', 'selectionerul nationalei', 'antrenor national',
      'jucator national', 'lot national', 'fotbal romanesc',
      'liga 1', 'liga nationala', 'liga a doua', 'prima liga',
      'super liga', 'campionatul national', 'cupa romaniei',
      'supercupa romaniei', 'meci de fotbal', 'meci amical',
      'meci oficial', 'joc de fotbal', 'stadion national',
      'arena nationala', 'ghencea', 'meci pe teren propriu',
      'meci in deplasare', 'meci acasa', 'repriza a doua',
      'repriza intai', 'minut de joc', 'timp suplimentar',
      'prelungiri', 'lovituri de departajare', 'penalty', 'cartonas rosu',
      'cartonas galben', 'gol inscris', 'gol marcat', 'autogol',
      'hat-trick', 'lovit bara', 'ocazie ratata', 'faza periculoasa',
      'scor final', 'rezultat final', 'victorie', 'infrangere',
      'egal alb', 'fara goluri', 'remiza', 'pct', 'punct obtinut',
      'clasament liga', 'pozitie in clasament', 'lider de clasament',
      'locul retrogradarii', 'loc de playoff', 'loc uefa',
      'uefa champions league', 'liga campionilor', 'uefa europa league',
      'uefa conference league', 'competitie europeana',
      'cupele europene', 'meci european', 'fcsb', 'cfr cluj',
      'universitatea craiova', 'rapid bucuresti', 'dinamo bucuresti',
      'steaua bucuresti', 'fc botosani', 'fc arges',
      'jucator de fotbal', 'fotbalist roman', 'atacant', 'fundas',
      'mijlocas', 'portar', 'golgheter', 'marcator',
      'cei mai buni jucatori', 'cel mai bun jucator',
      'jucator transferat', 'transfer record', 'transfer spectaculos',
      'clauza de reziliere', 'suma de transfer', 'contract nou',
      'prelungire contract', 'reziliere contract', 'agent fotbalist',
      'impresar', 'perioada de transferuri', 'fereastra de transferuri',
      'antrenor principal', 'staff tehnic', 'antrenor secund',
      'preparator fizic', 'antrenor demis', 'antrenor demisionat',
      'nou antrenor', 'tactică de joc', 'strategie', 'sistem de joc',
      'tenis romanesc', 'jucatoare de tenis', 'jucator de tenis',
      'simona halep', 'turneu de tenis', 'wimbledon', 'roland garros',
      'us open', 'australian open', 'grand slam', 'atp tour',
      'wta tour', 'clasament wta', 'clasament atp', 'loc in clasament',
      'meci de tenis', 'finala turneului', 'semifinala', 'sferturi de finala',
      'optimi de finala', 'turul 1', 'set castigat', 'break',
      'minge de meci', 'minge de set', 'handbal masculin',
      'handbal feminin', 'echipa de handbal', 'nationala de handbal',
      'csm bucuresti', 'potaissa turda', 'liga europeana',
      'champions league handbal', 'meci de handbal',
      'baschet romanesc', 'echipa de baschet', 'nationala de baschet',
      'u banca transilvania', 'meci de baschet', 'liga nationala baschet',
      'jocurile olimpice', 'olimpiada de vara', 'olimpiada de iarna',
      'paris 2024', 'los angeles 2028', 'echipa olimpica',
      'sportiv olimpic', 'medalie olimpica', 'medalie de aur',
      'medalie de argint', 'medalie de bronz', 'campion olimpic',
      'podium olimpic', 'natație romaneasca', 'david popovici',
      'campion mondial', 'campion european', 'record mondial',
      'record european', 'record national', 'performanta sportiva',
      'competitie internationala', 'competitie nationala',
      'sportiv roman', 'athlete roman', 'performanta',
      'gimnastica romaneasca', 'nadia comaneci', 'canotaj',
      'caiac canoe', 'atletism', 'maraton', 'circuit formula 1',
      'curse auto', 'moto gp', 'ciclism', 'arte martiale',
      'lupte greco-romane', 'judo', 'karate', 'box',
      'mma', 'kempo', 'volei', 'polo pe apa', 'schi',
      'patinaj', 'hochei pe gheata', 'bob', 'sanie',
      'biatlon', 'sarituri cu schiurile', 'sportivi de performanta',
      'doping sportiv', 'dopaj'
    ],

    'Vreme': [
      // Single words
      'vreme', 'furtuna', 'ninsori', 'zapada', 'zapada abundenta', 'canicula',
      'cod galben', 'ploaie', 'temperaturi', 'meteo', 'prognoza',
      'grindina', 'vant', 'inghet', 'viscol',
      // Multi-word phrases
      'prognoza meteo', 'prognoza vremii', 'serviciul meteo',
      'administrația națională de meteorologie', 'centru meteorologic',
      'meteorolog de serviciu', 'alerta meteo', 'avertizare meteo',
      'cod rosu', 'cod portocaliu', 'cod galben', 'cod de canicula',
      'cod de viscol', 'cod de ploi', 'cod de vant', 'cod de inghet',
      'avertizare nowcasting', 'avertizare imediata', 'avertizare cod',
      'vreme instabila', 'vreme rea', 'vreme capricioasa',
      'vreme frumoasa', 'vreme insorita', 'cer senin', 'cer innorat',
      'cer acoperit', 'nebulozitate ridicata', 'fara precipitatii',
      'precipitatii abundente', 'precipitatii moderate', 'precipitatii slabe',
      'ploi torentiale', 'ploi abundente', 'ploi insemnate',
      'ploi cu caracter torential', 'ploaie torentiala', 'cantitati de apa',
      'acumulari de apa', 'risc de inundatii', 'risc hidrometeorologic',
      'viituri pe rauri', 'rauri iesite din albie', 'debordare rauri',
      'inundatii locale', 'zone inundate', 'inundatii extinse',
      'ninsori abundente', 'ninsori insemnate', 'ninsori moderate',
      'ninsori slabe', 'viscol puternic', 'viscol', 'ninsoare abundenta',
      'strat de zapada', 'zapada proaspata', 'omăt', 'zapada viscolita',
      'troiene de zapada', 'drumuri blocate', 'drumuri inzapezite',
      'trafic blocat', 'circulatie rutiera afectata', 'accidente rutiere',
      'conditii de iarna', 'polei pe sosele', 'gheata pe carosabil',
      'gheata pe drum', 'suprafete inghetate', 'vreme de iarna',
      'sezon de iarna', 'val de frig', 'ger puternic', 'temperaturi negative',
      'temperaturi scazute', 'temperaturi minime', 'temperaturi sub zero',
      'grade celsius', 'minus grade', 'grade sub zero',
      'inghet la sol', 'inghet puternic', 'fenomene de inghet',
      'canicula puternica', 'val de caldura', 'caldura torida',
      'canicula extrema', 'temperaturi ridicate', 'temperaturi maxime',
      'temperaturi caniculare', 'temperaturi de foc', 'peste 40 grade',
      'peste 35 grade', 'disconfort termic', 'disconfort termic ridicat',
      'indice uv ridicat', 'expunere solara', 'risc de arsuri solare',
      'risc de deshidratare', 'risc pentru sanatate',
      'furtuna puternica', 'furtuna electrica', 'furtuni violente',
      'descarcari electrice', 'fulgere', 'intensificari ale vantului',
      'vant puternic', 'rafale de vant', 'vant cu rafale',
      'viteza vantului', 'vijelie', 'rafale peste',
      'grindina de mari dimensiuni', 'caderi de grindina',
      'grindina puternica', 'fenomene meteo extreme',
      'fenomene periculoase', 'vreme severa', 'vreme extrema',
      'conditii meteorologice', 'conditii meteo dificile',
      'maxima zilei', 'minima noptii', 'amplitudinea termica',
      'racire accentuata', 'racire a vremii', 'scaderea temperaturilor',
      'cresterea temperaturilor', 'incalzire', 'tendinta de incalzire',
      'regim termic', 'izotermă', 'front atmosferic', 'ciclon',
      'anticiclon', 'presiune atmosferica', 'presiune scazuta',
      'presiune ridicata', 'umiditate relativa', 'umiditate ridicata',
      'aer uscat', 'mase de aer', 'mase de aer rece',
      'mase de aer cald', 'mase de aer polar', 'curent oceanic',
      'curent continental', 'influenta oceanica', 'influenta continentala',
      'zona montana', 'zona de munte', 'peste 1800 metrii',
      'la munte', 'la altitudini', 'regiuni montane', 'carpatii',
      'zona de câmpie', 'zona de deal', 'regiuni de câmpie',
      'vest tarii', 'est tarii', 'nord tarii', 'sud tarii'
    ],
  };

  static Map<String, List<String>> storyTypeNegativeKeywords = {
    'Politică internă': [
      // Exclude international politics
      'presedintele sua', 'presedintele rusiei', 'presedintele frantei',
      'presedintele chinei', 'casa alba', 'kremlin', 'elysee',
      'summit nato', 'summit ue', 'summit european', 'summit g7', 'summit g20',
      'consiliul european', 'comisia europeana', 'bruxelles', 'strasbourg',
      'parlament european', 'alegerile europarlamentare',
      'conflict armat', 'razboi', 'invazie', 'sanctiuni internationale',
      'orientul mijlociu', 'razboi in ucraina',
      // Exclude sports federation politics
      'presedinte federatie', 'presedinte club', 'presedintele clubului',
      'presedintele federatiei', 'federatia romana de fotbal', 'frf',
      // Exclude business/economic summits
      'forum economic', 'summit economic', 'davos',
    ],

    'World': [
      // Exclude Romanian internal politics
      'guvernul romaniei', 'parlamentul romaniei', 'presedintele romaniei',
      'klaus iohannis', 'palatul cotroceni', 'camera deputatilor',
      'prim ministru roman', 'prim-ministru roman', 'guvern de la bucuresti',
      'ministru roman', 'coalitie de guvernare', 'coalitia psd-pnl',
      'marcel ciolacu', 'nicolae ciuca', 'nicusor dan', 'gabriela firea',
      'parlament de la bucuresti', 'curtea constitutionala',
      'politica romaneasca', 'scena politica romaneasca',
      'psd', 'pnl', 'usr', 'aur', 'udmr',
      'alegeri locale', 'alegeri parlamentare romanesti',
      'alegeri prezidentiale romania', 'la bucuresti',
      // Keep "romania in nato" and "romania in ue" in World, so don't exclude them
    ],
    'Business': [
      // Exclude government budgets (those are politics)
      'buget guvernamental', 'bugetul statului', 'buget de stat',
      'buget national',
    ],
    'Entertainment': [
      // Exclude news about entertainment industry business
      'industria filmului', 'piata cinematografica', 'box office record',
      // Exclude political/diplomatic cultural events
      'eveniment diplomatic', 'vizita de stat', 'spion',
    ],
    'Știință și Tehnologie': [
      // Exclude science education policy (that's politics)
      'reforma invatamant', 'ministrul educatiei', 'educatie nationala',
      'presedinte al romaniei',
      // Exclude tech business/economic news
      'actiuni apple', 'actiuni tesla', 'bursa tech',
    ],
    'Health': [
      // This is politics, not health
      'ministrul sanatatii', 'minister sanatatii', 'reforma sistemului sanitar',
      'buget sanatate', 'greva medicilor', 'sindicat medici',
      // Exclude health & beauty lifestyle content
      'rutina beauty', 'produse cosmetice', 'ingrijire ten',
    ],
    'Sport': [
      // Exclude gaming/esports
      'fotbal virtual', 'joc video', 'fifa game', 'esports', 'e-sports',
      'gaming', 'console', 'playstation', 'xbox',
      // Exclude sports betting/business
      'casa de pariuri', 'pariuri sportive', 'cota meci',
      // Exclude sports politics
      'scandal la federatie', 'alegeri federatie',
      // Exclude unrelated words that might appear in articles
      'autostraz', 'utilaj', 'autostrada', 'transport', 'securitate', 'militar',
      'nato', 'presedinte al romaniei',
    ],
    'Vreme': [
      // Exclude climate change politics/policy
      'politici climatice', 'summit climatic', 'acord climatic',
      'politica de mediu', 'trump', 'putin', 'razboi'
      // Exclude disaster response (that's politics/world news)
      'stare de urgenta', 'declaratie de dezastru', 'ajutor guvernamental',
    ],
  };
}